#ifndef GDOCUPDATESHEMA_H
#define GDOCUPDATESHEMA_H

#include <string>
#include <QString>
using namespace std;

struct GDocUpdateShema {

    string rawData = R"(
{
   "requests":[
      {
         "replaceAllText":{
            "replaceText":"%1",
            "containsText":{
               "text":"{{Urzad_Nazwa}}",
               "matchCase":false
            }
         }
      },
      {
         "replaceAllText":{
            "replaceText":"%2",
            "containsText":{
               "text":"{{Urzad_Adres}}",
               "matchCase":false
            }
         }
      },
      {
         "replaceAllText":{
            "replaceText":"%3",
            "containsText":{
               "text":"{{Urzad_Kod}}",
               "matchCase":false
            }
         }
      },
      {
         "replaceAllText":{
            "replaceText":"%4",
            "containsText":{
               "text":"{{Urzad_Miasto}}",
               "matchCase":false
            }
         }
      },
      {
         "replaceAllText":{
            "replaceText":"%5",
            "containsText":{
               "text":"{{Inwestycja_Nazwa}}",
               "matchCase":false
            }
         }
      },
      {
         "replaceAllText":{
            "replaceText":"%6",
            "containsText":{
               "text":"{{Inwestycja_dzialka}}",
               "matchCase":false
            }
         }
      },
      {
         "replaceAllText":{
            "replaceText":"%7",
            "containsText":{
               "text":"{{Inwestycja_Obreb}}",
               "matchCase":false
            }
         }
      },
      {
         "replaceAllText":{
            "replaceText":"%8",
            "containsText":{
               "text":"{{Inwestycja_Miasto}}",
               "matchCase":false
            }
         }
      },
      {
         "replaceAllText":{
            "replaceText":"%9",
            "containsText":{
               "text":"{{Inwestycja_Ewidencja}}",
               "matchCase":false
            }
         }
      },
      {
         "replaceAllText":{
            "replaceText":"%10",
            "containsText":{
               "text":"{{Inwestycja_Powiat}}",
               "matchCase":false
            }
         }
      },
      {
         "replaceAllText":{
            "replaceText":"%11",
            "containsText":{
               "text":"{{Inwestycja_wojewodztwo}}",
               "matchCase":false
            }
         }
      },
      {
         "replaceAllText":{
            "replaceText":"%12",
            "containsText":{
               "text":"{{Inwestor}}",
               "matchCase":false
            }
         }
      },
      {
         "replaceAllText":{
            "replaceText":"%16",
            "containsText":{
               "text":"{{Inwestycja_Sprawa}}",
               "matchCase":false
            }
         }
      },
      {
         "replaceAllText":{
            "replaceText":"%17",
            "containsText":{
               "text":"{{Tresc}}",
               "matchCase":false
            }
         }
      },
      {
         "replaceAllText":{
            "replaceText":"%18",
            "containsText":{
               "text":"{{Zalaczniki}}",
               "matchCase":false
            }
         }
      },
      {
         "replaceAllText":{
            "replaceText":"%19",
            "containsText":{
               "text":"{{Architekt_Imie}}",
               "matchCase":false
            }
         }
      },
      {
         "replaceAllText":{
            "replaceText":"%20",
            "containsText":{
               "text":"{{Architekt_telefon}}",
               "matchCase":false
            }
         }
      },
      {
         "replaceAllText":{
            "replaceText":"%21",
            "containsText":{
               "text":"{{Architekt_email}}",
               "matchCase":false
            }
         }
      },
      {
         "replaceAllText":{
            "replaceText":"%22",
            "containsText":{
               "text":"{{DATA}}",
               "matchCase":false
            }
         }
      }
}
)";



};

#endif // GDOCUPDATESHEMA_H
