#ifndef KERNELCOMMON_H
#define KERNELCOMMON_H


enum DATA_TYPES{
    ARCHITEKT_DATA,
    URZEDY_DATA,
    INWESTOR_DATA,
    INWESTYCJE_DATA,
    PROJEKTY_DATA,
    DECYZJE_DATA,
    PRACOWNIA_DATA
};
#endif // KERNELCOMMON_H
